# Generated by Django 3.1.4 on 2021-03-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20201202_1658'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.infopage'),
        ),
        migrations.AddField(
            model_name='languagevariant',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.infopage'),
        ),
    ]
