# Generated by Django 3.1.4 on 2021-03-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20201202_1658'),
        ('dictionary', '0002_auto_20210303_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pos',
            field=models.CharField(default='Noun', max_length=32),
        ),
        migrations.AlterField(
            model_name='language',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.infopage'),
        ),
        migrations.AlterField(
            model_name='languagevariant',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.infopage'),
        ),
    ]
