# Generated by Django 2.2.4 on 2020-11-30 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('short_title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('text', models.TextField()),
                ('secret_text', models.TextField()),
                ('next_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.InfoPage')),
            ],
        ),
    ]
