# Generated by Django 2.2.4 on 2020-12-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_remove_infopage_secret_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=64)),
                ('loc_type', models.TextField(choices=[('village', 'Small Village or Town'), ('city', 'Major City'), ('region', 'General Region')], default='village', max_length=7)),
                ('page', models.ForeignKey(default='Introduction', on_delete=django.db.models.deletion.SET_DEFAULT, to='wiki.InfoPage')),
            ],
        ),
    ]
