# Generated by Django 2.2.4 on 2020-12-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_maplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maplocation',
            name='y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
