# Generated by Django 3.1.4 on 2021-03-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20201202_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretPassword',
            fields=[
                ('password', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordUnlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.secretpassword')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.infosecret')),
            ],
        ),
    ]
